apiVersion: v1
kind: Service
metadata:
  namespace: comical-site-062020
  name: comical-site-loadbalancer
spec:
  selector:
    app: comical-site-app
  ports:
    - port: 80
      targetPort: 9000
  type: LoadBalancer
