apiVersion: v1
kind: Service
metadata:
  namespace: comical-site
  name: comical-site-app
  annotations:
    # service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "comical.site"
    # service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    # service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
spec:
  type: LoadBalancer
  # externalTrafficPolicy: Cluster
  selector:
    app: comical-site-app
  ports:
  - port: 80
    name: http
    targetPort: 9005
  - port: 443
    name: https
    targetPort: 9005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: comical-site
  name: comical-site-app
spec:
  selector:
    matchLabels:
      app: comical-site-app
  replicas: 1
  template:
    metadata:
      labels:
        app: comical-site-app
    spec:
      containers:
      - name: comical-site-app
        image: prequod/comical-site:nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 9005
          protocol: TCP
