apiVersion: v1
kind: Service
metadata:
  namespace: comical-site-caddy
  name: comical-site-caddy
spec:
  selector:
    app: comical-site-caddy
  ports:
    - port: 80
      targetPort: 9000
  type: LoadBalancer
